#os: Visual Studio 2013 - GCE

only_commits:
#  message: /build/
  files:
  - Nunit3Tests/

build:
  verbosity: minimal

before_build:
- nuget restore

#test:
#  categories:
#    only:
#    - A
#    - B
