#os: Visual Studio 2013

install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-nuget-3-4-0.ps1'))

skip_commits:
#  message: /build/
  files:
  - Nunit3Tests/
  - NunitTestsX86\**\*.cs

build:
  verbosity: minimal

before_build:
- nuget restore

#test:
#  categories:
#    only:
#    - A
#    - B
